/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RecordAnchor } from './RecordAnchor.js';
export * as factories from './factories/index.js';
export { RecordAnchor__factory } from './factories/RecordAnchor__factory.js';