/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RecordAnchorInterface extends Interface {
    getFunction(nameOrSignature: "anchorRecord" | "owner" | "renounceOwnership" | "transferOwnership" | "verifyRecord"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "RecordAnchored"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorRecord', values: [BytesLike, string, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyRecord', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'anchorRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyRecord', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordAnchoredEvent {
      export type InputTuple = [sha256Hash: BytesLike, recordType: string, recordId: string, submitter: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [sha256Hash: string, recordType: string, recordId: string, submitter: string, timestamp: bigint];
      export interface OutputObject {sha256Hash: string, recordType: string, recordId: string, submitter: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RecordAnchor extends BaseContract {
    
    connect(runner?: ContractRunner | null): RecordAnchor;
    waitForDeployment(): Promise<this>;

    interface: RecordAnchorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorRecord: TypedContractMethod<
      [sha256Hash: BytesLike, recordType: string, recordId: string, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyRecord: TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [[boolean, string, string, string, bigint] & {exists: boolean, recordType: string, recordId: string, submitter: string, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorRecord'): TypedContractMethod<
      [sha256Hash: BytesLike, recordType: string, recordId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyRecord'): TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [[boolean, string, string, string, bigint] & {exists: boolean, recordType: string, recordId: string, submitter: string, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RecordAnchored'): TypedContractEvent<RecordAnchoredEvent.InputTuple, RecordAnchoredEvent.OutputTuple, RecordAnchoredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RecordAnchored(bytes32,string,string,address,uint256)': TypedContractEvent<RecordAnchoredEvent.InputTuple, RecordAnchoredEvent.OutputTuple, RecordAnchoredEvent.OutputObject>;
      RecordAnchored: TypedContractEvent<RecordAnchoredEvent.InputTuple, RecordAnchoredEvent.OutputTuple, RecordAnchoredEvent.OutputObject>;
    
    };
  }